# Generated by Django 4.2.5 on 2023-10-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
