# Generated by Django 4.2.5 on 2023-10-30 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_comment_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
    ]
