# Generated by Django 4.2.5 on 2023-10-30 19:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_comment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
