# Generated by Django 4.2.5 on 2023-10-30 19:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
