# Generated by Django 4.2.5 on 2023-10-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(),
        ),
    ]
